theme: jekyll-theme-tactile
title: Terrarium TV Official Website
description: This is the only Terrarium TV Official Website. Terrarium TV app has been shut down and discontinued. All its related operations have been ceased officially.
show_downloads: false
